In [1]:
x1 = [2,3,5,6]
x2 = [6,9,2,5]
l = []

In [2]:
for i ,j in zip(x1 , x2):
    l.append(i+j)

In [3]:
for i in l:
    print(i)

8
12
7
11


In [4]:
import numpy as np
import time


In [5]:
x1 = np.array([2,3,5,6])
x2 = np.array([6,9,2,5])
x3 = x1 + x2

In [6]:
print(x3)

[ 8 12  7 11]


In [7]:
np.dot(x1,x2)

np.int64(79)

In [8]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)
a

array([0.46606582, 0.30073114, 0.58964005, ..., 0.40911789, 0.18665879,
       0.75542413], shape=(1000000,))

In [9]:
tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("vectoried version:" + str(1000*(toc-tic)) + "ms")
print(c)

vectoried version:3.9899349212646484ms
249859.76324295293


In [10]:
c = 0
tic = time.time()
for i in range(1000000):
    c+= a[i]*b[i]
toc = time.time()

print(c)
print("for loop:" + str(1000*(toc-tic)) + "ms")


249859.763242954
for loop:1309.6082210540771ms


In [11]:
import pandas as pd

data = {"Color": ["Red", "Green", "Blue", "Green", "Red"]}
df = pd.DataFrame(data)

print(df)


   Color
0    Red
1  Green
2   Blue
3  Green
4    Red


In [12]:
# Convert categorical 'Color' column into one-hot encoding
encoded = pd.get_dummies(df, columns=["Color"]).astype(int)

print(encoded)
print(encoded.dtypes)


   Color_Blue  Color_Green  Color_Red
0           0            0          1
1           0            1          0
2           1            0          0
3           0            1          0
4           0            0          1
Color_Blue     int64
Color_Green    int64
Color_Red      int64
dtype: object


In [13]:

a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix = np.array(a)

print("NumPy Matrix:")
print(matrix)


NumPy Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
complex_matrix = np.array(a[2], dtype=complex)
complex_matrix

array([7.+0.j, 8.+0.j, 9.+0.j])

In [15]:
com = np.array([2 ,3.2,4j])
com

array([2. +0.j, 3.2+0.j, 0. +4.j])

In [16]:

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])


C = A + B
D = np.dot(A,B)
E = A*B


print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nA + B =\n", C)
print("E \n" ,E)
print("D \n" , D)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

A + B =
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
E 
 [[ 9 16 21]
 [24 25 24]
 [21 16  9]]
D 
 [[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [17]:
import numpy as np

# Example dataset with 2 rows
X = np.array([
    [12, 11, 27, 13, 12, 1],  # row1 with bias=1
    [10,  9, 25, 11, 14, 1]   # row2 with bias=1
], dtype=float)

y = np.array([58, 52], dtype=float)

# Compute least-norm solution using pseudoinverse
theta = np.linalg.pinv(X) @ y

print("Parameters (a1..a5, b):")
print(theta)

# Test predictions (should match y closely)
y_pred = X @ theta
print("Predictions:", y_pred)
print("Actual:", y)


Parameters (a1..a5, b):
[0.66260472 0.62782432 1.18431074 0.69738512 0.1721249  0.0347804 ]
Predictions: [58. 52.]
Actual: [58. 52.]


In [18]:
import numpy as np

# Example dataset with 2 rows
X = np.array([
    [ 1, 2, 1, 1, 1,1],  # row1 with bias=1
    [1,  7, 3, 2, 1,1]   # row2 with bias=1
], dtype=float)

y = np.array([5, 8], dtype=float)

# Compute least-norm solution using pseudoinverse
theta = np.linalg.pinv(X) @ y

print("Parameters (a1..a5, b):")
print(theta)




Parameters (a1..a5, b):
[1.0990099  0.31683168 0.34653465 0.72277228 1.0990099  1.0990099 ]


In [19]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]
