In [45]:
import numpy as np



In [30]:
X = np.array([
    [1,2,1,1,1],
    [1,7,3,2,1]
])

y = np.array([5,8])

X , y

(array([[1, 2, 1, 1, 1],
        [1, 7, 3, 2, 1]]),
 array([5, 8]))

In [31]:
print("shape of X is" , X.shape)
print("shape of y is" , y.shape)

shape of X is (2, 5)
shape of y is (2,)


In [ ]:
X_b = np.hstack([np.ones((X.shape[0],1)), X])  #Add bias
X_b

array([[1., 1., 2., 1., 1., 1.],
       [1., 1., 7., 3., 2., 1.]])

In [ ]:
parameters  = np.linalg.pinv(X_b) @ y  #find parameters

In [34]:
parameters

array([1.0990099 , 1.0990099 , 0.31683168, 0.34653465, 0.72277228,
       1.0990099 ])

In [44]:
y_train_pred = X_b @ parameters
print(y_train_pred)

[5. 8.]


In [42]:
x3 = np.array([1,1,2,1,1,1])

In [38]:
y_pred = x3 @ parameters
y_pred

np.float64(4.999999999999998)