In [1]:
x1 = [2,3,5,6]
x2 = [6,9,2,5]
l = []

In [3]:
for i ,j in zip(x1 , x2):
    l.append(i+j)

In [4]:
for i in l:
    print(i)

8
12
7
11


In [10]:
import numpy as np
import time


In [6]:
x1 = np.array([2,3,5,6])
x2 = np.array([6,9,2,5])
x3 = x1 + x2

In [8]:
print(x3)

[ 8 12  7 11]


In [9]:
np.dot(x1,x2)

np.int64(79)

In [16]:
a = np.random.rand(1000000)
b = np.random.rand(1000000)
a

array([0.43789611, 0.27192124, 0.82784674, ..., 0.45189756, 0.40962844,
       0.79596572], shape=(1000000,))

In [15]:
tic = time.time()
c = np.dot(a,b)
toc = time.time()

print("vectoried version:" + str(1000*(toc-tic)) + "ms")
print(c)

vectoried version:1.9946098327636719ms
249776.91889119713


In [14]:
c = 0
tic = time.time()
for i in range(1000000):
    c+= a[i]*b[i]
toc = time.time()

print(c)
print("for loop:" + str(1000*(toc-tic)) + "ms")


249776.9188912045
for loop:1442.0850276947021ms


In [17]:
import pandas as pd

data = {"Color": ["Red", "Green", "Blue", "Green", "Red"]}
df = pd.DataFrame(data)

print(df)


   Color
0    Red
1  Green
2   Blue
3  Green
4    Red


In [20]:
# Convert categorical 'Color' column into one-hot encoding
encoded = pd.get_dummies(df, columns=["Color"]).astype(int)

print(encoded)
print(encoded.dtypes)


   Color_Blue  Color_Green  Color_Red
0           0            0          1
1           0            1          0
2           1            0          0
3           0            1          0
4           0            0          1
Color_Blue     int64
Color_Green    int64
Color_Red      int64
dtype: object


In [21]:

a = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

matrix = np.array(a)

print("NumPy Matrix:")
print(matrix)


NumPy Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
complex_matrix = np.array(a[2], dtype=complex)
complex_matrix

array([7.+0.j, 8.+0.j, 9.+0.j])

In [25]:
com = np.array([2 ,3.2,4j])
com

array([2. +0.j, 3.2+0.j, 0. +4.j])

In [26]:

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


B = np.array([
    [9, 8, 7],
    [6, 5, 4],
    [3, 2, 1]
])


C = A + B

print("Matrix A:\n", A)
print("\nMatrix B:\n", B)
print("\nA + B =\n", C)

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

A + B =
 [[10 10 10]
 [10 10 10]
 [10 10 10]]
